### ISSUE TITLE
Hunter Douglas API

### ISSUE THREAD

**Issue by andrewfg** [bujvary/hubitat#1]
I posted a message on the Hubitat forum asking if you have the contact details of Dave at Hunter Douglas concerning their API as I am looking for the meaning of their `shadeData` JSON `capabilities` element in order to solve this [Issue](https://github.com/openhab/openhab-addons/issues/11557) on OpenHAB, and I was wondering if you could kindly put me in touch?

**Comment by andrewfg** [comment]
I did not yet get a response from Hunter Douglas yet. However from doing some extensive Googling of shade JSON payloads, I was able to build the following (tentative) table of capabilities. => Any further inputs would be appreciated.

![image](https://user-images.githubusercontent.com/893994/143320873-5f29c2bc-1e51-4d3b-8ed8-003a1eddccec.png)

**Comment by bujvary** [comment]
<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
margin-left:.25in;line-height:normal;background:white'><span style='font-size:
10.5pt;font-family:"Helvetica",sans-serif;mso-fareast-font-family:"Times New Roman";
color:black;mso-color-alt:windowtext'>The Hunter Douglas developer recommended the
use of the “capabilities” field instead of the “type” field as that is easier
to work with. Here is the shade capability information from Hunter Douglas:</span><b><span
style='font-size:10.5pt;font-family:"Helvetica",sans-serif;mso-fareast-font-family:
"Times New Roman"'><o:p></o:p></span></b></p>



Capability Value | Shade Type | Shade Description
-- | -- | --
0 | Bottom Up | Shades with standard bottom-up operation   such as Alustra Woven Textures, Roller, Screen & Banded Shades,   Duette/Applause Standard, Design Studio shades, Solera, Vignette Modern Roman   Shades Provenance Woven Wood Shades.
1 | Bottom Up Tilt 90° | Shades with Bottom-Up lift and 90° Tilt.   Includes Pirouette, Silhouette, Silhouette A Deux Front Shade.
2 | Bottom Up Tilt 180° | Lift and Tilt Horizontal Blind (Not sold in   USA at this time).
3 | Vertical | Vertically oriented shades with horizontal   traverse operation only. Include Skyline Left Stack, Right Stack, Split   Stack; Provenance Vertical Drapery Left Stack, Right Stack, Split Stack;   Duette/Applause Vertiglide Left Stack, Right Stack.
4 | Vertical Tilt 180° | Vertically oriented shades with horizontal   traverse operation plus 180° Tilt. Includes Luminette Left Stack, Right Stack   and Split Stack.
5 | Tilt Only 180° | Products with tilt-only operation such as   Parkland, EverWood, Modern Precious Metals and Palm Beach Shutters
6 | Top Down | Top-Down (only) operation includes   Duette/Applause Top-Down.
7 | Top Down Bottom Up | Shades with Top-Down/Bottom-Up (TDBU)   operation or stacking Duolite operation including Duette/Applause TDBU,   Solera TDBU, Vignette TDBU, Provenance TDBU; Alustrao Woven Textureso Romans   TDBU, Duette/Applause Duolite.
8 | Duolite Lift | Shades with lift only Duolite operation eg.   Vignette Duolite, Roller/Screen Duolite (not released).
9 | Duolite Lift and Tilt 90° | Duolite lift operation plus 90° tilt   operation. Includes: Silhouette Duolite.



<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

**Comment by andrewfg** [comment]
Cool. Many thanks @bujvary !

It fully confirms what I had discovered elsewhere, which is a great relief.

In case you need it, for openHAB I have summarised the shade capabilities (and types) in the new [ShadeCapabilitiesDatabase class](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java)
